package com.smile.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.smile.plugins.model.Restaurant;
import com.smile.plugins.service.RestaurantLocalServiceUtil;

/**
 * The extended model base implementation for the Restaurant service. Represents a row in the &quot;MealTime_Restaurant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RestaurantImpl}.
 * </p>
 *
 * @author guillaume Lenoir
 * @see RestaurantImpl
 * @see com.smile.plugins.model.Restaurant
 * @generated
 */
public abstract class RestaurantBaseImpl extends RestaurantModelImpl
    implements Restaurant {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a restaurant model instance should use the {@link Restaurant} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RestaurantLocalServiceUtil.addRestaurant(this);
        } else {
            RestaurantLocalServiceUtil.updateRestaurant(this);
        }
    }
}
